package br.com.usinasantafe.cmm.utils

const val BASE_SHARE_PREFERENCES = "cmm"
const val BASE_DB = "cmm.db"
const val VERSION_DB = 999

const val BASE_SHARE_PREFERENCES_TABLE_CONFIG = "config"
const val BASE_SHARE_PREFERENCES_TABLE_HEADER_MOTO_MEC = "header_moto_mec"
const val BASE_SHARE_PREFERENCES_TABLE_NOTE_MOTO_MEC = "note_moto_mec"
const val BASE_SHARE_PREFERENCES_TABLE_HEADER_CHECK_LIST = "header_check_list"

const val QTD_TABLE = 8f

const val TB_ACTIVITY = "tb_activity"
const val TB_BOCAL = "tb_bocal"
const val TB_COLAB = "tb_colab"
const val TB_COMPONENTE = "tb_componente"
const val TB_EQUIP = "tb_equip"
const val TB_FRENTE = "tb_frente"
const val TB_ITEM_CHECK_LIST = "tb_item_check_list"
const val TB_ITEM_OS_MECAN = "tb_item_os_mecan"
const val TB_LEIRA = "tb_leira"
const val TB_MOTOMEC = "tb_motomec"
const val TB_OS = "tb_os"
const val TB_PNEU = "tb_pneu"
const val TB_PRESSAO_BOCAL = "tb_pressao_bocal"
const val TB_PRODUTO = "tb_produto"
const val TB_PROPRIEDADE = "tb_propriedade"
const val TB_R_ACTIVITY_STOP = "tb_r_activity_stop"
const val TB_R_EQUIP_ACTIVITY = "tb_r_equip_activity"
const val TB_R_EQUIP_PNEU = "tb_r_equip_pneu"
const val TB_FUNCTION_ACTIVITY_STOP = "tb_function_activity_stop"
const val TB_R_OS_ACTIVITY = "tb_r_os_activity"
const val TB_SERVICO = "tb_servico"
const val TB_STOP = "tb_stop"
const val TB_TURN = "tb_turn"

const val TB_HEADER_MOTO_MEC = "tb_header_moto_mec"
const val TB_NOTE_MOTO_MEC = "tb_note_moto_mec"

const val WEB_ALL_ACTIVITY = "activity.php"
const val WEB_ALL_BOCAL = "bocal.php"
const val WEB_ALL_COLAB = "colab.php"
const val WEB_ALL_COMPONENTE = "componente.php"
const val WEB_ALL_FRENTE = "frente.php"
const val WEB_ALL_ITEM_OS_MECAN = "item-os-mecan.php"
const val WEB_ALL_LEIRA = "leira.php"
const val WEB_ALL_MOTOMEC = "motomec.php"
const val WEB_ALL_OS = "os.php"
const val WEB_ALL_PRESSAO_BOCAL = "pressao-bocal.php"
const val WEB_ALL_PROPRIEDADE = "propriedade.php"
const val WEB_ALL_R_ACTIVITY_STOP = "r-activity-stop.php"
const val WEB_ALL_R_EQUIP_PNEU = "r-equip-pneu.php"
const val WEB_ALL_R_FUNCAO_ATIV_PARADA = "r-funcao-ativ-parada.php"
const val WEB_ALL_R_OS_ATIV = "r-os-ativ.php"
const val WEB_ALL_SERVICO = "servico.php"
const val WEB_ALL_STOP = "stop.php"
const val WEB_ALL_TURN = "turn.php"

const val WEB_SAVE_TOKEN = "find-token.php"
const val WEB_OS_LIST_BY_NRO_OS = "os-list-by-nro-os.php"
const val WEB_R_OS_ACTIVITY_LIST_BY_NRO_OS = "r-os-activity-list-by-nro-os.php"
const val WEB_EQUIP_LIST_BY_ID_EQUIP = "equip-list-by-id-equip.php"
const val WEB_R_EQUIP_ACTIVITY_LIST_BY_ID_EQUIP = "r-equip-activity-list-by-id-equip.php"
const val WEB_CHECK_CHECK_LIST_BY_NRO_EQUIP = "check-update-check-list-by-nro-equip.php"
const val WEB_ITEM_CHECK_LIST_LIST_BY_NRO_EQUIP = "item-check-list-list-by-nro-equip.php"

const val WEB_SAVE_MOTO_MEC = "save-moto-mec.php"