package br.com.usinasantafe.cmm.utils

enum class StatusSend { STARTED, SEND, SENT }
enum class Errors { FIELD_EMPTY, TOKEN, UPDATE, EXCEPTION, INVALID, HEADER_EMPTY }
enum class TypeButton { NUMERIC, CLEAN, OK, UPDATE }
enum class FlagUpdate { OUTDATED, UPDATED }
enum class Status { OPEN, CLOSE, FINISH }

enum class StatusLeira { LIBERADA, DESCARGA, CARGA }
enum class TypeOper { ATIVIDADE, PARADA }
enum class TypeActivity { PERFORMANCE, TRANSHIPMENT, IMPLEMENT, REEL, WINDROW, TRANSPORT_SUGARCANE }
enum class TypeStop { CHECKLIST, IMPLEMENT, CALIBRATION, REEL }
enum class FunctionItemMenu { ITEM_NORMAL, FINISH_HEADER, RETURN_LIST, PERFORMANCE, TRANSHIPMENT, IMPLEMENT, HOSE_COLLECTION, MECHANICAL_MAINTENANCE, TIRE, REEL }

enum class TypeView { ITEM, BUTTON }
enum class TypeEquip { NORMAL, FERT }
enum class LevelUpdate { RECOVERY, CLEAN, SAVE, GET_TOKEN, SAVE_TOKEN, FINISH_UPDATE_INITIAL, FINISH_UPDATE_COMPLETED }
enum class OptionRespCheckList { ACCORDING, ANALYZE, REPAIR }

enum class FlowNote { WORK, STOP, PERFORMANCE, TRANSHIPMENT, IMPLEMENT, HOSE_COLLECTION, NOTE_MECHANICAL, FINISH_MECHANICAL, TIRE_INFLATION, TIRE_CHANGE, REEL, FINISH_HEADER, RETURN_LIST }
enum class FlowApp { HEADER_INITIAL, NOTE_WORK, NOTE_STOP, HEADER_FINISH, CHECK_LIST }
