package br.com.usinasantafe.cmm.utils

enum class StatusSend { STARTED, SEND, SENT }
enum class Errors { FIELD_EMPTY, TOKEN, UPDATE, EXCEPTION,
    INVALID, HEADER_EMPTY, NOTE_MECHANICAL_OPEN,
    WITHOUT_NOTE_TRANSHIPMENT, TIME_INVALID_TRANSHIPMENT, LAST_NOTE_WORK,
    PRE_CEC_STARTED, WITHOUT_EXIT_MILL_PRE_CEC, WITH_ARRIVAL_FIELD_PRE_CEC,
    WITHOUT_LOADING_INPUT, WITHOUT_LOADING_COMPOSTING
}
enum class TypeButton { NUMERIC, CLEAN, OK, UPDATE }
enum class FlagUpdate { OUTDATED, UPDATED }
enum class Status { OPEN, CLOSE, FINISH }

enum class TypeNote { WORK, STOP }
enum class TypeActivity { PERFORMANCE, TRANSHIPMENT, IMPLEMENT, REEL, WINDROW, TRANSPORT_SUGARCANE }
enum class TypeStop { CHECKLIST, IMPLEMENT, CALIBRATION, REEL }

enum class TypeView { ITEM, BUTTON }
enum class TypeEquip { NORMAL, FERT }
enum class LevelUpdate { RECOVERY, CLEAN, SAVE, GET_TOKEN, SAVE_TOKEN, FINISH_UPDATE_INITIAL, FINISH_UPDATE_COMPLETED }
enum class OptionRespCheckList { ACCORDING, ANALYZE, REPAIR }

enum class FlowApp { HEADER_INITIAL, NOTE_WORK, NOTE_STOP, HEADER_FINISH, CHECK_LIST }

enum class FlowComposting { INPUT, COMPOUND }
enum class FlowTire { INFLATION, CHANGE }
enum class FlowEquipNote { MAIN, SECONDARY }
enum class StatusTranshipment { OK, WITHOUT_NOTE, TIME_INVALID }

enum class TypeMsg { ITEM_NORMAL, NOTE_FINISH_MECHANICAL, RETURN_MILL }
enum class StatusPreCEC { EMPTY, EXIT_MILL, ARRIVAL_FIELD,  }