package br.com.usinasantafe.cmm.lib

const val BASE_SHARE_PREFERENCES = "cmm"
const val BASE_DB = "cmm.db"
const val VERSION_DB = 999

const val BASE_SHARE_PREFERENCES_TABLE_CONFIG = "config"
const val BASE_SHARE_PREFERENCES_TABLE_HEADER_MOTO_MEC = "header_moto_mec"
const val BASE_SHARE_PREFERENCES_TABLE_NOTE_MOTO_MEC = "note_moto_mec"
const val BASE_SHARE_PREFERENCES_TABLE_HEADER_CHECK_LIST = "header_check_list"
const val BASE_SHARE_PREFERENCES_TABLE_RESP_ITEM_CHECK_LIST_LIST = "resp_item_check_list_list"
const val BASE_SHARE_PREFERENCES_TABLE_PRE_CEC = "pre_cec"
const val BASE_SHARE_PREFERENCES_TABLE_TRAILER_LIST = "trailer_list"
const val BASE_SHARE_PREFERENCES_TABLE_EQUIP = "equip"



const val TB_ACTIVITY = "tb_activity"
const val TB_COLAB = "tb_colab"
const val TB_EQUIP = "tb_equip"
const val TB_FUNCTION_ACTIVITY = "tb_function_activity"
const val TB_FUNCTION_STOP = "tb_function_stop"
const val TB_ITEM_CHECK_LIST = "tb_item_check_list"
const val TB_ITEM_MENU  = "tb_item_menu"
const val TB_NOZZLE = "tb_nozzle"
const val TB_PRESSURE = "tb_pressure"
const val TB_OS = "tb_os"
const val TB_R_ACTIVITY_STOP = "tb_r_activity_stop"
const val TB_R_EQUIP_ACTIVITY = "tb_r_equip_activity"
const val TB_R_OS_ACTIVITY = "tb_r_os_activity"
const val TB_R_ITEM_MENU_STOP  = "tb_r_item_menu_stop"
const val TB_STOP = "tb_stop"
const val TB_TURN = "tb_turn"

const val TB_HEADER_MOTO_MEC = "tb_header_moto_mec"
const val TB_ITEM_MOTO_MEC = "tb_item_moto_mec"
const val TB_HEADER_CHECK_LIST = "tb_header_check_list"
const val TB_ITEM_RESP_CHECK_LIST = "tb_item_resp_check_list"
const val TB_MECHANIC = "tb_mechanic"
const val TB_INPUT_COMPOSTING = "tb_input_composting"
const val TB_COMPOUND_COMPOSTING = "tb_compound_composting"
const val TB_PERFORMANCE = "tb_performance"
const val TB_COLLECTION = "tb_collection"


const val WEB_ALL_ACTIVITY = "activity.php"
const val WEB_ALL_COLAB = "colab.php"
const val WEB_ALL_EQUIP = "equip.php"
const val WEB_ALL_FUNCTION_ACTIVITY = "function-activity.php"
const val WEB_ALL_FUNCTION_STOP = "function-stop.php"
const val WEB_ALL_ITEM_MENU = "item-menu.php"
const val WEB_ALL_NOZZLE = "nozzle.php"
const val WEB_ALL_OS = "os.php"
const val WEB_ALL_PRESSURE = "pressure.php"
const val WEB_ALL_R_ACTIVITY_STOP = "r-activity-stop.php"
const val WEB_ALL_R_OS_ACTIVITY = "r-os-activity.php"
const val WEB_ALL_R_ITEM_MENU_STOP = "r-item-menu-stop.php"
const val WEB_ALL_STOP = "stop.php"
const val WEB_ALL_TURN = "turn.php"

const val WEB_SAVE_TOKEN = "find-token.php"
const val WEB_OS_LIST_BY_NRO_OS = "os-list-by-nro-os.php"
const val WEB_R_OS_ACTIVITY_LIST_BY_NRO_OS = "r-os-activity-list-by-nro-os.php"
const val WEB_R_EQUIP_ACTIVITY_LIST_BY_ID_EQUIP = "r-equip-activity-list-by-id-equip.php"
const val WEB_CHECK_CHECK_LIST_BY_NRO_EQUIP = "check-update-check-list-by-nro-equip.php"
const val WEB_ITEM_CHECK_LIST_LIST_BY_NRO_EQUIP = "item-check-list-list-by-nro-equip.php"

const val WEB_SAVE_MOTO_MEC = "save-moto-mec.php"
const val WEB_SAVE_CHECK_LIST = "save-check-list.php"

const val PMM = "PMM"
const val ECM = "ECM"
const val PCOMP = "PCOMP"
const val PCOMP_INPUT = "PCOMP_INSUMO"
const val PCOMP_COMPOUND = "PCOMP_COMPOSTO"

const val WORK = "TRABALHANDO"
const val STOP = "PARADO"
const val PERFORMANCE = "RENDIMENTO"
const val TRANSHIPMENT = "NOVO_TRANSBORDO"
const val IMPLEMENT = "TROCAR_IMPLEMENTO"
const val HOSE_COLLECTION = "RECOLHIMENTO_MANGUEIRA"
const val NOTE_MECHANICAL = "APONTAR_MANUTENCAO"
const val FINISH_MECHANICAL = "FINALIZAR_MANUTENCAO"
const val TIRE_INFLATION = "CALIBRAGEM_PNEU"
const val TIRE_CHANGE = "TROCAR_PNEU"
const val REEL = "APONTAR_CARRETEL"
const val ITEM_NORMAL = "ITEM_NORMAL"
const val MECHANICAL = "MECANICO"
const val TIRE = "PNEU"
const val FERTIGATION = "FERTIRRIGACAO"
const val CERTIFICATE = "CERTIFICADO"
const val EXIT_MILL = "SAIDA_USINA"
const val EXIT_FIELD = "SAIDA_CAMPO"
const val FIELD_ARRIVAL = "CHEGADA_CAMPO"
const val RETURN_MILL = "RETORNO_USINA"
const val WEIGHING = "PESAGEM"
const val UNCOUPLING_TRAILER = "DESENGATE_CARRETA"
const val COUPLING_TRAILER = "ENGATE_CARRETA"
const val WEIGHING_TARE = "PESAGEM_TARA"
const val EXIT_SCALE = "SAIDA_BALANCA"
const val LOADING_INPUT = "CARREGAMENTO_INSUMO"
const val LOADING_COMPOUND = "CARREGAMENTO_COMPOSTO"
const val WEIGHING_LOADED = "PESAGEM_CARREGADO"
const val EXIT_TO_DEPOSIT = "SAIDA_PARA_DEPOSITO"
const val EXIT_TO_FIELD = "SAIDA_PARA_CAMPO"
const val CHECK_WILL = "VERIFICAR_LEIRA"
const val UNLOADING_INPUT = "DESCARREGAMENTO_INSUMO"
const val WAITING_UNLOADING = "AGUARDANDO_DESCARREGAMENTO"
const val HISTORY = "HISTORICO"
const val RETURN_WORK = "VOLTAR_TRABALHO"
const val UNCOUPLING_FIELD = "DESENGATE_CAMPO"
const val COUPLING_FIELD = "ENGATE_CAMPO"
const val WAITING_LOADING = "AGUARDANDO_CARREGAMENTO"
const val LOADING = "CARREGAMENTO"
const val WEIGHING_SCALE = "PESAGEM_BALANCA"
const val UNCOUPLING_COURTYARD = "DESENGATE_PATIO"
const val COUPLING_COURTYARD = "ENGATE_PATIO"
const val STOP_COURTYARD = "PARADA_PATIO"
const val UNLOADING_HILO = "DESCARREGAMENTO_HILO"
const val FINISH_DISCHARGE = "FIM_DESCARGA"
const val WAITING_ALLOCATION = "AGUARDANDO_ALOCACAO"
const val EXIT_LOADING = "SAIDA_CARREGAMENTO"
const val EXIT_UNLOADING = "SAIDA_DESCARREGAMENTO"
const val UNLOADING_COMPOUND = "CARREGAMENTO_COMPOSTO"

const val MSG_CHECK_OS = "Verificando OS no Web Service"

const val ERROR_HEADER_WITHOUT_NOTE = "Header without note!"
const val ERROR_TIME_INVALID = "Time invalid!"
const val ERROR_WITHOUT_NOTE_OR_LAST = "Without note or last is not type work!"
const val ERROR_NOTE_MECHANIC = "Note mechanic NOT open!"
const val ERROR_WITHOUT_NOTE = "Without Note!"
const val ERROR_PRE_CEC_STARTED = "PRE CEC already started!"
const val ERROR_WITHOUT_EXIT_MILL_PRE_CEC = "Without exit mill in PRE CEC!"
const val ERROR_WITH_FIELD_ARRIVAL_PRE_CEC = "With arrival field in PRE CEC!"
const val ERROR_NEED_UNCOUPLING_TRAILER = "Need uncoupling trailer!"
const val ERROR_NEED_COUPLING_TRAILER = "Need coupling trailer!"
const val ERROR_WITHOUT_LOADING_INPUT = "Without loading input!"
const val ERROR_WITHOUT_LOADING_COMPOSTING = "Without loading composting!"
const val ERROR_FIELD_EMPTY = "Field Empty!"