package br.com.usinasantafe.cmm.lib

enum class StatusSend { STARTED, SEND, SENT }
enum class Errors { FIELD_EMPTY, TOKEN, UPDATE, EXCEPTION,
    INVALID, HEADER_EMPTY, NOTE_MECHANICAL_OPEN,
    WITHOUT_NOTE_TRANSHIPMENT, TIME_INVALID_TRANSHIPMENT, LAST_NOTE_WORK,
    PRE_CEC_STARTED, WITHOUT_EXIT_MILL_PRE_CEC, WITH_FIELD_ARRIVAL_PRE_CEC,
    WITHOUT_LOADING_INPUT, WITHOUT_LOADING_COMPOSTING,
    NEED_UNCOUPLING_TRAILER, NEED_COUPLING_TRAILER, WITHOUT_NOTE, INVALID_HOUR_METER,
    INVALID_VALUE, INVALID_COLLECTION, INVALID_CLOSE_PERFORMANCE, INVALID_CLOSE_COLLECTION
}
enum class TypeButton { NUMERIC, CLEAN, OK, UPDATE }
enum class FlagUpdate { OUTDATED, UPDATED }
enum class Status { OPEN, CLOSE, FINISH }

enum class TypeNote { WORK, STOP }
enum class TypeActivity { PERFORMANCE, TRANSHIPMENT, IMPLEMENT, COLLECTION, WINDROW, TRANSPORT_SUGARCANE }
enum class TypeStop { CHECKLIST, IMPLEMENT, CALIBRATION, REEL }

enum class TypeEquip { NORMAL, REEL_FERT, TRANSHIPMENT, IMPLEMENT, MOTOR_PUMP, CHARGER, TRAILER }
enum class LevelUpdate { RECOVERY, CLEAN, SAVE, GET_TOKEN, SAVE_TOKEN, FINISH_UPDATE_INITIAL, FINISH_UPDATE_COMPLETED }
enum class OptionRespCheckList { ACCORDING, ANALYZE, REPAIR }

enum class FlowApp { HEADER_INITIAL, NOTE_WORK, NOTE_STOP, HEADER_FINISH, CHECK_LIST, TRANSHIPMENT, REEL_FERT, PERFORMANCE }

enum class FlowComposting { INPUT, COMPOUND }
enum class FlowTire { INFLATION, CHANGE }
enum class FlowEquipNote { MAIN, SECONDARY }
enum class FlowTrailer { UNCOUPLING, COUPLING }
enum class StatusTranshipment { OK, WITHOUT_NOTE, TIME_INVALID }

enum class TypeMsg { ITEM_NORMAL, NOTE_FINISH_MECHANICAL, RETURN_MILL, UNCOUPLING_TRAILER }
enum class StatusPreCEC { EXIT_MILL, FIELD_ARRIVAL, EXIT_FIELD }

enum class StatusComposting { LOAD, UNLOADING }